export enum EModels {
    VOLKSWAGEN_TOUAREG = "Touareg",
    VOLKSWAGEN_ARTEON = "Arteon",
    VOLKSWAGEN_ATLAS = "Atlas",
    VOLKSWAGEN_BORA = "Bora",
    AUDI_5000 = "5000",
    AUDI_80 = "80",
    AUDI_A3 = "A3",
    AUDI_A4 = "A4",
    BMW_3_SERIES_GT = "3 Series GT",
    BMW_4_SERIES_GRAN_COUPE = "4 Series Gran Coupe",
    BMW_5_SERIES_GT = "5 Series GT",
    BMW_6_SERIES_GT = "6 Series GT",
    CHEVROLET_AVEO = "Aveo",
    CHEVROLET_BOLT_EV = "Bolt EV",
    CHEVROLET_CAMARO = "Camaro",
    CHEVROLET_CAPTIVA = "Captiva",
    LEXUS_CT = "CT",
    LEXUS_HS = "HS",
    LEXUS_LC = "LC",
    LEXUS_LF = "LF"
}