export enum ERegions {
  Kyiv = "Kyiv",
  Chernihiv = "Chernihiv",
  Zhytomyr = "Zhytomyr",
  Rivne = "Rivne",
  Volyn = "Volyn",
  Lviv = "Lviv",
  Ternopil = "Ternopil",
  Ivano_Frankivsk = "Ivano-Frankivsk",
  Zakarpattia = "Zakarpattia",
  Chernivtsi = "Chernivtsi",
  Khmelnytskyi = "Khmelnytskyi",
  Vinnytsia = "Vinnytsia",
  Cherkasy = "Cherkasy",
  Odesa = "Odesa",
  Mykolaiv = "Mykolaiv",
  Kirovohrad = "Kirovohrad",
  Kherson = "Kherson",
  Crimea = "Crimea",
  Zaporizhzhia = "Zaporizhzhia",
  Dnipropetrovsk = "Dnipropetrovsk",
  Poltava = "Poltava",
  Sumy = "Sumy",
  Kharkiv = "Kharkiv",
  Donetsk = "Donetsk",
  Luhansk = "Luhansk",
}
